apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-multus
  name: nephio-workload-cluster-multus
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-multus'
spec:
  annotations:
    approval.nephio.org/policy: initial
    approval.nephio.org/delay: 2m
  upstream:
    package: multus
    repo: nephio-example-packages
    revision: v1
  downstream:
    package: nephio-workload-cluster-multus
    repo: mgmt-staging
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: nephio-workload-cluster
