apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-repo
  name: nephio-workload-cluster-workload-cluster-repo
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-repo'
spec:
  annotations:
    approval.nephio.org/policy: initial
    approval.nephio.org/delay: 2m
  upstream:
    package: repository
    repo: nephio-example-packages
    revision: v3
  downstream:
    package: nephio-workload-cluster-workload-cluster-repo
    repo: mgmt
  injectors:
  - kind: WorkloadCluster
    name: nephio-workload-cluster
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: nephio-workload-cluster
