apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-vlanindex
  name: example-vlanindex
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-vlanindex'
spec:
  annotations:
    approval.nephio.org/policy: initial
    approval.nephio.org/delay: 2m
  upstream:
    package: vlanindex
    repo: nephio-example-packages
    revision: v1
  downstream:
    package: example-vlanindex
    repo: mgmt
  injectors:
  - kind: WorkloadCluster
    name: example
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
